var skill = [
    {"name":"Adrenaline"},
    {"name":"Affinity Sliding"},
    {"name":"Agitator"}, {"name":"Airborne"},
    {"name":"Aquatic Expert"},
    {"name":"Artillery"},
    {"name":"Attack Boost"},
    {"name":"BBQ Master"},
    {"name":"Blast Attack"},
    {"name":"Blast Resistance"},
    {"name":"Bleeding Resistance"},
    {"name":"Blight Resistance"},
    {"name":"Blindsider"},
    {"name":"Bludgeoner"},
    {"name":"Bombardier"},
    {"name":"Botanist"},
    {"name":"Bow Charge Plus"},
    {"name":"Capacity Boost"},
    {"name":"Capture Master"},
    {"name":"Carving Pro"},
    {"name":"Cliffhanger"},
    {"name":"Constitution"},
    {"name":"Critical Boost"},
    {"name":"Critical Draw"},
    {"name":"Critical Element"},
    {"name":"Critical Eye"},
    {"name":"Critical Status"},
    {"name":"Defense Boost"},
    {"name":"Detector"},
    {"name":"Divine Blessing"},
    {"name":"Dragon Attack"},
    {"name":"Dragon Resistance"},
    {"name":"Dungmaster"},
    {"name":"Earplugs"},
    {"name":"Effluvia Resistance"},
    {"name":"Effluvial Expert"},
    {"name":"Entomologist"},
    {"name":"Evade Extender"},
    {"name":"Evade Window"},
    {"name":"Fire Attack"},
    {"name":"Fire Resistance"},
    {"name":"Flinch Free"},
    {"name":"Focus"},
    {"name":"Forager's Luck"},
    {"name":"Fortify"},
    {"name":"Free Elem/Ammo Up"},
    {"name":"Free Meal"},
    {"name":"Geologist"},
    {"name":"Good Luck"},
    {"name":"Guard"},
    {"name":"Guard Up"},
    {"name":"Guts"},
    {"name":"Handicraft"},
    {"name":"Hasten Recovery"},
    {"name":"Heat Guard"},
    {"name":"Health Boost"},
    {"name":"Heavy Artillery"},
    {"name":"Heroics"},
    {"name":"Honey Hunter"},
    {"name":"Horn Maestro"},
    {"name":"Hunger Resistance"},
    {"name":"Ice Attack"},
    {"name":"Ice Resistance"},
    {"name":"Intimidator"},
    {"name":"Iron Skin"},
    {"name":"Item Prolonger"},
    {"name":"Jump Master"},
    {"name":"Latent Power"},
    {"name":"Leap of Faith"},
    {"name":"Marathon Runner"},
    {"name":"Master Fisher"},
    {"name":"Master Gatherer"},
    {"name":"Master Mounter"},
    {"name":"Master's Touch"},
    {"name":"Maximum Might"},
    {"name":"Mind's Eye/Ballistics"},
    {"name":"Muck Resistance"},
    {"name":"Mushroomancer"},
    {"name":"Non-elemental Boost"},
    {"name":"Normal Shots"},
    {"name":"Nullify Wind Pressure"},
    {"name":"Palico Rally"},
    {"name":"Paralysis Resistance"},
    {"name":"Paralysis Attack"},
    {"name":"Partbreaker"},
    {"name":"Peak Performance"},
    {"name":"Piercing Shots"},
    {"name":"Poison Attack"},
    {"name":"Poison Duration Up"},
    {"name":"Poison Resistance"},
    {"name":"Power Prolonger"},
    {"name":"Pro Transporter"},
    {"name":"Protective Polish"},
    {"name":"Punishing Draw"},
    {"name":"Quick Sheath"},
    {"name":"Razor Sharp/Spare Shot"},
    {"name":"Recovery Speed"},
    {"name":"Recovery Up"},
    {"name":"Resentment"},
    {"name":"Resuscitate"},
    {"name":"Scenthound"},
    {"name":"Scholar"},
    {"name":"Scoutfly Range Up"},
    {"name":"Sleep Attack"},
    {"name":"Sleep Resistance"},
    {"name":"Slinger Capacity"},
    {"name":"Slugger"},
    {"name":"Special Ammo Boost"},
    {"name":"Speed Crawler"},
    {"name":"Speed Eating"},
    {"name":"Speed Sharpening"},
    {"name":"Sporepuff Expert"},
    {"name":"Spread/Power Shots"},
    {"name":"Stamina Cap Up"},
    {"name":"Stamina Surge"},
    {"name":"Stamina Thief"},
    {"name":"Stealth"},
    {"name":"Stun Resistance"},
    {"name":"Super Recovery"},
    {"name":"Thunder Attack"},
    {"name":"Thunder Resistance"},
    {"name":"Tool Specialist"},
    {"name":"Tremor Resistance"},
    {"name":"Water Attack"},
    {"name":"Water Resistance"},
    {"name":"Weakness Exploit"},
    {"name":"Wide-Range"},
    {"name":"Windproof"}
]